version: '3'
services:
  api-staging:
    build: .
    ports:
    - "8000:80"
    environment:
    - ASPNETCORE_ENVIRONMENT=Staging
  api-production:
    build: .
    ports:
    - "80:80"
    environment:
    - ASPNETCORE_ENVIRONMENT=Production